### ISSUE TITLE
I can't build iOS project because framework "CouchbaseLite" not found in xcode

### ISSUE THREAD

**Issue by AlexShavkunov** [jeffdgr8/kotbase#22]
Hi! I have a compose multiplatform project with two platforms - iOS and android. I tried to use `"dev.kotbase:couchbase-lite:3.1.3-1.1.0"` and `"dev.kotbase:couchbase-lite-paging:3.1.3-1.1.0"` implementation in **commonMain** and it builds good in android, but not in iOS. The iOS project doesn't use cocoapods, only manual integration.
The project doesn't build and throw this error:
<img width="1106" alt="Снимок экрана 2024-02-14 в 00 11 10" src="https://github.com/jeffdgr8/kotbase/assets/29992069/efad2537-c8ec-4454-92d0-79a617a8c7c0">

Can you tell me what I do wrong?

**Comment by jeffdgr8** [comment]
On native platforms, you need to link to the **CouchbaseLite** native framework or binary. I've found it easiest to use the CocoaPods plugin [as described in the docs](https://kotbase.dev/current/platforms/#ios-macos), but you can also link to the framework manually as well.

The **getting-started** example app [does this](https://github.com/jeffdgr8/kotbase/blob/8280f63c62cc9b4013be3a7964fa1a5e93148c8a/examples/getting-started/shared/build.gradle.kts#L14-L30) by linking to the framework within the repository. You could also pair this with a Gradle task to download the framework to the build directory before linking. You can download the native framework [here](https://www.couchbase.com/downloads/?family=couchbase-lite) or find the link in the [CocoaPods repo](https://github.com/CocoaPods/Specs/blob/master/Specs/3/a/6/CouchbaseLite/3.1.4/CouchbaseLite.podspec.json).

The **getting-started-compose** example [links to the framework via CocoaPods](https://github.com/jeffdgr8/kotbase/blob/8280f63c62cc9b4013be3a7964fa1a5e93148c8a/examples/getting-started-compose/composeApp/build.gradle.kts#L24-L27). You just need to configure your iOS app with CocoaPods and [use the .xcworkspace instead of .xcodeproj](https://kotbase.dev/current/getting-started/#ios-app_1).

**Comment by jeffdgr8** [comment]
Great! That is another option I forgot to mention, to link the framework in the Xcode project.
